name: terraform-eks

on:
  push:
    branches: ["main"]
  # pull_request:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: us-east-1

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Set up Terraform (version 1.6.0 or higher)
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2  # Use v2 for the latest version support
        with:
          terraform_version: ">= 1.6.0"  # Ensure the version is at least 1.6.0

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        # working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init

      - name: Terraform State Debug
        run: |
          terraform workspace show
          terraform providers
          terraform state list || true
          
      - name: Terraform Validate
        # working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out tfplan -input=false -no-color
        env:
          TF_VAR_user_for_admin_role: ${{ secrets.TF_USER_FOR_ADMIN_ROLE }}
          TF_VAR_user_for_dev_role: ${{ secrets.TF_USER_FOR_DEV_ROLE }}
          TF_VAR_user_for_FullAdminAccess: ${{ secrets.TF_USER_FOR_FULLADMINACCESS }}
      
      - name: Terraform Apply (main only)
        if: github.ref == 'refs/heads/main'
        run: terraform apply -input=false -auto-approve tfplan
        env:
          TF_VAR_user_for_admin_role: ${{ secrets.TF_USER_FOR_ADMIN_ROLE }}
          TF_VAR_user_for_dev_role: ${{ secrets.TF_USER_FOR_DEV_ROLE }}
          TF_VAR_user_for_FullAdminAccess: ${{ secrets.TF_USER_FOR_FULLADMINACCESS }}


